### ISSUE TITLE
Error when converting multipe po files to the same directory

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [luukfroling/sphinx-translation-button#1]
```bash
$ python poToMo.py "gettext/intro.po" "./locale/nl/LC_MESSAGES/intro.mo"
[Translator3000] Compiling PO file to MO file... gettext/intro.po -> ./locale/nl/LC_MESSAGES/intro.mo
Traceback (most recent call last):
  File "C:\Users\tomvanwoudenbe\Git\Sandbox-GH\book\poToMo.py", line 25, in <module>
    compile_po_to_mo(po_file, mo_file)
  File "C:\Users\tomvanwoudenbe\Git\Sandbox-GH\book\poToMo.py", line 10, in compile_po_to_mo
    os.makedirs(os.path.dirname(mo_file))
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] Kan geen bestand maken dat al bestaat: './locale/nl/LC_MESSAGES'
(sandbox)
```

**Comment by luukfroling** [comment]
Fixed! put a condition in to check if the file already exists
